[tool.poetry]
name = "tr_core"
version = "0.1.0"
description = ""
authors = ["yada <trojblue@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
gradio-client = "^1.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
